# Generated by Django 4.1.12 on 2024-07-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysite',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/', verbose_name='アイコン'),
        ),
    ]
