# Generated by Django 4.1.12 on 2024-07-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0002_studysite_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysite',
            name='icon',
        ),
        migrations.AddField(
            model_name='studysite',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='問題画像'),
        ),
    ]
