# Generated by Django 4.1.12 on 2024-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0003_remove_studysite_icon_studysite_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysite',
            name='code',
        ),
        migrations.RemoveField(
            model_name='studysite',
            name='description',
        ),
        migrations.AddField(
            model_name='studysite',
            name='answer',
            field=models.TextField(blank=True, verbose_name='解答'),
        ),
        migrations.AddField(
            model_name='studysite',
            name='question',
            field=models.TextField(blank=True, verbose_name='問題'),
        ),
    ]
