# Generated by Django 4.1.12 on 2024-07-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0004_remove_studysite_code_remove_studysite_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='studysite',
            name='tags',
            field=models.ManyToManyField(blank=True, to='studysite.tag'),
        ),
    ]
