# Generated by Django 4.1.12 on 2024-07-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0005_tag_studysite_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysite',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
