# Generated by Django 3.2.25 on 2024-08-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0006_studysite_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysite',
            name='answer',
            field=models.TextField(blank=True, verbose_name='解説'),
        ),
        migrations.AlterField(
            model_name='studysite',
            name='image',
            field=models.FileField(blank=True, upload_to='image/', verbose_name='問題画像'),
        ),
    ]
