# Generated by Django 3.2.25 on 2024-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0007_auto_20240806_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysite',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
