# Generated by Django 3.2.25 on 2024-08-11 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studysite', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysite',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
