# Generated by Django 3.2.25 on 2024-08-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0010_studysite_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
