# Generated by Django 3.2.25 on 2024-09-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0012_taggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysite',
            name='tag_groups',
            field=models.ManyToManyField(blank=True, related_name='studysites', to='studysite.TagGroup'),
        ),
        migrations.AlterField(
            model_name='studysite',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='studysites', to='studysite.Tag'),
        ),
    ]
