# Generated by Django 3.2.25 on 2024-09-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0013_auto_20240904_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysite',
            name='tags',
        ),
        migrations.AddField(
            model_name='taggroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studysite',
            name='tag_groups',
            field=models.ManyToManyField(blank=True, to='studysite.TagGroup'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
