# Generated by Django 3.2.25 on 2024-09-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studysite', '0015_remove_taggroup_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
